name: 'elastic_dbt_interview'
version: '1.0.0'
config-version: 2

flags:
  send_anonymous_usage_stats: False

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"

models:
  elastic_dbt_interview:
    +database: dbt
    intermediate:
      +materialized: table
      +schema: intermediate
    marts:
      +schema: marts
      +materialized: table
    reporting:
      +schema: reporting
      +materialized: table
    staging:
      +schema: staging
      +materialized: view

vars:
  "dbt_date:time_zone": "Europe/Berlin"
